# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new build to firebase app distribution"
  lane :firebase do |options|

    # Run
    # fastlane beta versionNumber:"1.0.0" to explicitly set the version number or
    # fastlane beta versionChange:"minor|major|patch" to explicitly increase version
    # fastlane beta to increase build number
    if (options[:versionChange]=='major')
        gradle(task: "doMajorVersionIncrement")
    elsif (options[:versionChange]=='minor')
        gradle(task: "doMinorVersionIncrement")
    elsif (options[:versionChange]=='patch')
        gradle(task: "doPatchVersionIncrement")
    else
        gradle(task: "doBuildNumberIncrement")
    end

    notes = options[:notes] || changelog_from_git_commits(commits_count: 1, merge_commit_filtering: "exclude_merges")

    gradle(
      task: "assemble",
      flavor: "Development",
      build_type: "Release"
    )

    firebase_app_distribution(
        app: "1:1004594285090:android:939ac9d43ac11f4e53587b",
        release_notes: notes,
        firebase_cli_path: '/usr/local/bin/firebase'
    )

    git_commit(path: "version.properties", message: "chore: Update version.properties")
    push_to_git_remote(
        local_branch: "develop",
        remote_branch: "develop",
        tags: false
    )
  
  end

end
